### ISSUE TITLE
OCI Terraform Provider on Macbook M1

### ISSUE THREAD

**Issue by perlporter** [jpetazzo/ampernetacle#11]
I am having trouble executing your code, see: 

Do you have any tips, to help me ?

Provider registry.terraform.io/hashicorp/oci v4.62.0 does not have a package available for your current platform, darwin_arm64.

Thank you...

**Comment by jpetazzo** [comment]
Hi!

Apparently that provider is not available for the mac M1, at least not yet, from what I can see here:

https://releases.hashicorp.com/terraform-provider-oci/4.62.0/

Do you have the "rosetta" emulation environment on your mac M1?
(I think it should help, but I'm not sure. I don't have a M1 myself to test...)

**Comment by perlporter** [comment]
Hi @jpetazzo !

I'm trying using Rosetta2, but not work too, see:  

➜ ampernetacle (main) ✔ uname -a
Darwin toothless.ramenzoni.lan 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 x86_64
➜ ampernetacle (main) ✔ arch 
i386

Error: Incompatible provider version
Provider registry.terraform.io/hashicorp/oci v4.62.0 does not have a package available for your current platform, darwin_arm64.

Is there anything else you could test?

**Comment by jpetazzo** [comment]
I see!

I did a little bit of reasearch and found [issue hashicorp/terraform#27257](https://github.com/hashicorp/terraform/issues/27257#issuecomment-825102330) which has some instructions to compile a provider from source.

I don't have an M1 machine here to try it out unfortunately...

I wonder if it might be easier to run it within a Docker container using QEMU emulation.

Do you have Docker installed on your machine, per chance?

**Comment by rafaelzimmermann** [comment]
I would suggest to create an instance on Oracle cloud and run from there.
The way to authenticate with oci changes a bit, but it is not complicated

https://docs.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm#How2

**Comment by rafaelzimmermann** [comment]
Otherwise I was also able to run it using Roseta
