### ISSUE TITLE
ssh timeout

### ISSUE THREAD

**Issue by whoiswentz** [jpetazzo/ampernetacle#12]
So, my problem is, after terraform finished the creation of all underlying infrastructure when I try to connect in some node I always receive the same error:

```shell
user@MacBook-Pro ampernetacle % ssh -i id_rsa -l k8s xxx.xxx.xxx.xx
ssh: connect to host xxx.xxx.xxx.xx port 22: Operation timed out
```

I simply followed the README.md

**Comment by jpetazzo** [comment]
Hi!

Do you have the same problems with all 4 nodes? (Let me know if you need help to find the IP addresses of the other nodes.)

And if you try with `ping`, do you get a reply or also a time out?

**Comment by whoiswentz** [comment]
Hi, thanks for answering. Yes, I got the same problem with all my 4 nodes.

I tried the `ping` command and I got a response back

```shell
64 bytes from xxx.xxx.xx.xxx: icmp_seq=1 ttl=51 time=205.851 ms
64 bytes from xxx.xxx.xx.xxx: icmp_seq=2 ttl=51 time=214.076 ms
64 bytes from xxx.xxx.xx.xxx: icmp_seq=3 ttl=51 time=352.204 ms
```

**Comment by jpetazzo** [comment]
The ping seems a bit high, but it shouldn't be a problem. (It will be a bit annoying later when we get the cluster to work, because the `kubectl` commands might be a bit slow, but it shouldn't prevent SSH.)

Is this a brand new OCI account?

And, just to be sure --- you can SSH to other machines alright?

**Comment by whoiswentz** [comment]
Yes, I created this account yesterday and no I can't ssh other machines I created a new one and tried with the same .pub that was generated for my cluster

**Comment by jpetazzo** [comment]
Hi!

Were you able to figure it out? Since it doesn't work on Digital Ocean either it's probably not a problem with OCI, but who knows.

**Comment by whoiswentz** [comment]
Hi Jerôme, I haven't tried again, I will set up other my older macbook to try ssh through it

**Comment by whoiswentz** [comment]
So, I tried to ssh into the cluster on another machine and it work, so probably is my machine
