### ISSUE TITLE
Switch availability domain

### ISSUE THREAD

**Issue by omurilo** [jpetazzo/ampernetacle#13]
Hi @jpetazzo, nice work bro!

Can I switch to a different availability domain? How?

**Comment by jpetazzo** [comment]
Thank you! :pray: 

Yes thanks to a PR by @uknbr it is possible to change the availability domain with the `availability_domain` variable.

You can edit it in `variables.tf` or set it like other Terraform variables. Perhaps I'll add some more explanations in the README if you think it's necessary :)

**Comment by caetano-felipe** [comment]
Hello @jpetazzo, how you doing?
I'm trying to change the default value of the variable, but without success. For example I change the default value from 0 to 1 and I get this error:
Error: Invalid index
│ 
│   on main.tf line 27, in resource "oci_core_instance" "_":
│   27:   availability_domain = data.oci_identity_availability_domains._.availability_domains[var.availability_domain].name
│     ├────────────────
│     │ data.oci_identity_availability_domains._.availability_domains is list of object with 1 element
│     │ var.availability_domain is 1
│ 
│ The given key does not identify an element in this collection value: the given index is greater than or equal to the length of the collection.

**Comment by uknbr** [comment]
Hello,

Probably you are using region which contains only one AD. I'd suggest to switch to US East (Ashburn) where there are 3 ADs.

**Comment by visued** [comment]
> only

+1

how to switch region ?

**Comment by caetano-felipe** [comment]
opa beleza @uknbr ? Cara como faz pra mudar de região? Ao tentar ali pela interface dando um subscribe em outra região ele gera essa mensagem:
 "You have exceeded the maximum number of regions allowed for your tenancy. See the [Limits, Quotas and Usage](https://cloud.oracle.com/limits) page for more detail."

**Comment by uknbr** [comment]
> opa beleza @uknbr ? Cara como faz pra mudar de região? Ao tentar ali pela interface dando um subscribe em outra região ele gera essa mensagem: "You have exceeded the maximum number of regions allowed for your tenancy. See the [Limits, Quotas and Usage](https://cloud.oracle.com/limits) page for more detail."

Eai, blz? Então cara, sou novo na OCI, sempre usei US East (Ashburn) tanto na UI quanto no CLI.

**Comment by fserve** [comment]
@caetano-felipe @uknbr for free oci accounts you cant change region.

Para contas gratuitas voce não pode mudar a região.
