### ISSUE TITLE
kubeadm-join.sh

### ISSUE THREAD

**Issue by diegostammer** [jpetazzo/ampernetacle#15]
Fiquei 3 dias tentando criar o cluster até que finalmente consegui.
Coloquei o apply em loop devido ao "Out of Host Capacity". 

`while true
do
    sleep 5; terraform apply -auto-approve && break
done`

Então primeiramente foram criados os 3 workers e, por último, o control-plane.
Só que devido a esta sequência, nenhum worker node juntou-se ao control-plane.
Tive que conectar manualmente em cada worker node e executar o **kubeadm-join.sh**.
Seria interessante então executar o **kubeadm-join.sh** somente após o control-plane estar pronto.

**Comment by jpetazzo** [comment]
Obrigado pelo relatório!

Acrescentei um "while curl ... sleep" no roteiro do kubeadm-join. Espero que ajude com esta edição.
