### ISSUE TITLE
shutdown/destroy the cluster

### ISSUE THREAD

**Issue by brunoaleixo** [jpetazzo/ampernetacle#17]
Hi
First, thanks for sharing the knowledge.
I have a doubt about turning off the cluster in the LinuxTips video it says a "cluster forever", but can I leave it turned on?

**Comment by fserve** [comment]
Yes, you can leave it on

**Comment by jpetazzo** [comment]
Hi!

Yes, you can leave it on, but personally I tend to shut it down when I'm done with it, to free up resources for others.

(I saw many other people mentioning that they had problems getting a cluster because it said "out of capacity" 😅)

Cheers,
