### ISSUE TITLE
Erro terraform apply

### ISSUE THREAD

**Issue by jonathanbrito2** [jpetazzo/ampernetacle#2]
Boa tarde, 

Alguém passou por esse erro ?

oci_core_instance._["3"]: Creation complete after 4m1s 
null_resource.wait_for_kube_apiserver: Creating...
null_resource.wait_for_kube_apiserver: Provisioning with 'local-exec'...
null_resource.wait_for_kube_apiserver (local-exec): Executing: ["cmd" "/C" "while ! curl -k https://xxx.70.196.103:6443; do\r\n  sleep 1\r\ndone\r\n"]
null_resource.wait_for_kube_apiserver (local-exec): 'while' não é reconhecido como um comando interno
null_resource.wait_for_kube_apiserver (local-exec): ou externo, um programa operável ou um arquivo em lotes.
╷
│ Error: local-exec provisioner error
│
│   with null_resource.wait_for_kube_apiserver,
│   on kubeconfig.tf line 3, in resource "null_resource" "wait_for_kube_apiserver":
│    3:   provisioner "local-exec" {
│
│ Error running command 'while ! curl -k https://xxx.70.196.103:6443; do
│   sleep 1
│ done
│ ': exit status 1. Output: 'while' não é reconhecido como um comando interno
│ ou externo, um programa operável ou um arquivo em lotes.

**Comment by jonathanbrito2** [comment]
Ignorei o arquivo kubeconfig.tf e tudo funcionou perfeitamente.

**Comment by jpetazzo** [comment]
Oh! Qual OS é esse? Linux ou outro?

**Comment by jpetazzo** [comment]
Acho que meu kubeconfig.tf não funciona com Windows... Se for o caso, atualizarei o README.

**Comment by jpetazzo** [comment]
Acho que devo tentar usar algo que funcione da mesma forma com Linux e Windows. Vou tentar encontrar uma solução melhor!

**Comment by jpetazzo** [comment]
Talvez eu tenha uma solução, mas usa o Docker. Isso seria aceitável?

**Comment by jonathanbrito2** [comment]
> Talvez eu tenha uma solução, mas usa o Docker. Isso seria aceitável?

Sim, mas teria um file.tf para instalar e configurar o Docker como pre requisito ?

**Comment by diogenesc** [comment]
No wsl2, consegui resolver trocando o tipo de quebra de linha para LF, que antes era CRLF. Depois da alteração tudo foi aplicado normalmente.

**Comment by jpetazzo** [comment]
Graças ao grande trabalho feito no #12, agora também deve ser possível rodar no Windows! Sinta-se à vontade para tentar e nos avisar se funciona para você agora.
