### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by HailsonJunior** [jpetazzo/ampernetacle#22]
Depois de criar os recursos fiquei aguardando por 25 minutos o control plane ficar disponível, mas nunca termina a tentativa do curl:

```bash
null_resource.wait_for_kube_apiserver (local-exec): curl: (7) Failed to connect to 144.22.149.148 port 6443: No route to host
null_resource.wait_for_kube_apiserver: Still creating... [25m36s elapsed]
null_resource.wait_for_kube_apiserver (local-exec):   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
null_resource.wait_for_kube_apiserver (local-exec):                                  Dload  Upload   Total   Spent    Left  Speed
null_resource.wait_for_kube_apiserver (local-exec):   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
null_resource.wait_for_kube_apiserver (local-exec):   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
null_resource.wait_for_kube_apiserver (local-exec): curl: (7) Failed to connect to 144.22.149.148 port 6443: No route to host
```

**Comment by bl4cktux89** [comment]
aparentemente essa porta não está aberta, usei o nmap para verificar e só consigo ver a porta 22 do ssh
![Screenshot_20220304_014902](https://user-images.githubusercontent.com/60237707/156701591-b4043cb6-2e6b-441d-a4c1-029a48619b17.png)

**Comment by bl4cktux89** [comment]
fiz um teste da minha workstation apontando para a instância na OCI e o retorno que tive é esse, a única porta que aparentemente está aberta é a TCP 22, usada para conexões SSH
![Screenshot_20220304_015623](https://user-images.githubusercontent.com/60237707/156702044-0d665767-e787-40ee-bac4-990e6cab9027.png)

**Comment by bl4cktux89** [comment]
usei o netstat dentro do node, mas pelo output, o nó não está escutando na porta especificada no terraform
![Screenshot_20220304_021600](https://user-images.githubusercontent.com/60237707/156703827-3e72e008-af3d-4fae-b2fa-12cd7c987644.png)

**Comment by nelsonmedeirosti** [comment]
Na verdade a porta está escutando via tcp, o que pode ser conferido com a opçao t (tcp) em vez de u (udp):

![Captura de tela de 2022-03-12 16-13-49](https://user-images.githubusercontent.com/58531269/158031776-2f66c725-9c69-4ac8-b818-fd571d6adc7c.png)

Consegui acesso ao executar um flush do netfilter no node 1:

node1#: netfilter-persistent flush

**Comment by andre-rodovalho** [comment]
2hrs quebrando cabeca aqui, `netfilter-persistent flush` no node1 resolveu, muito obrigado!

Eu tinha parado o processo, pra voltar e terminar a instalacao, rodei `terraform apply` novamente.

**Comment by jpetazzo** [comment]
This should now be fixed - thank you for reporting  it!
