### ISSUE TITLE
Error: 500-InternalError

### ISSUE THREAD

**Issue by faustosm** [jpetazzo/ampernetacle#23]
Error: 500-InternalError 
│ Provider version: 4.62.0, released on 2022-02-03. This provider is 4 Update(s) behind to current. 
│ Service: Core Instance 
│ Error Message: Out of host capacity. 
│ OPC request ID: d2aad3db605100b13fd8e768a3839636/8883E6ABFC2F5495AEAF3298B65C49A5/554BC3D0F5153961E5A14167AD49493C 
│ Suggestion: The service for this resource encountered an error. Please contact support for help with service: Core Instance
│ 
│ 
│   with oci_core_instance._["3"],
│   on main.tf line 24, in resource "oci_core_instance" "_":
│   24: resource "oci_core_instance" "_" {
│ 
╵
╷
│ Error: 500-InternalError 
│ Provider version: 4.62.0, released on 2022-02-03. This provider is 4 Update(s) behind to current. 
│ Service: Core Instance 
│ Error Message: Out of host capacity. 
│ OPC request ID: dbb0f7923e0f157569de3542d835d024/4333AD7FB18CDE289B702ABF111B9E45/0DA2636C4307FDBFB5DCA93310738F0F 
│ Suggestion: The service for this resource encountered an error. Please contact support for help with service: Core Instance
│ 
│ 
│   with oci_core_instance._["2"],
│   on main.tf line 24, in resource "oci_core_instance" "_":
│   24: resource "oci_core_instance" "_" {
│ 
╵
╷
│ Error: 500-InternalError 
│ Provider version: 4.62.0, released on 2022-02-03. This provider is 4 Update(s) behind to current. 
│ Service: Core Instance 
│ Error Message: Out of host capacity. 
│ OPC request ID: 803eb6480ee346882363c0506cc48bae/EBEF8857E071F51AE59BE1071CFB9A58/07CC0AF17F089E1E78CC50EC5507EA13 
│ Suggestion: The service for this resource encountered an error. Please contact support for help with service: Core Instance
│ 
│ 
│   with oci_core_instance._["4"],
│   on main.tf line 24, in resource "oci_core_instance" "_":
│   24: resource "oci_core_instance" "_" {
│ 
╵
╷
│ Error: 500-InternalError 
│ Provider version: 4.62.0, released on 2022-02-03. This provider is 4 Update(s) behind to current. 
│ Service: Core Instance 
│ Error Message: Out of host capacity. 
│ OPC request ID: e64c4814ade6cb674323295ef6879eb1/2E1D42479A56E6E68964FB31D4D6987E/081D60AA75E9F4F9171491EF2F24A1B2 
│ Suggestion: The service for this resource encountered an error. Please contact support for help with service: Core Instance
│ 
│ 
│   with oci_core_instance._["1"],
│   on main.tf line 24, in resource "oci_core_instance" "_":
│   24: resource "oci_core_instance" "_" {

**Comment by bl4cktux89** [comment]
i had the same problem, this is happening because of the provider is out of capacity, you must reduce the number of instances and the memory in the variables.tf file just like below:

```
variable "how_many_nodes" {
  type    = number
  default = 1
}

variable "availability_domain" {
  type    = number
  default = 0
}

variable "ocpus_per_node" {
  type    = number
  default = 1
}

variable "memory_in_gbs_per_node" {
  type    = number
  default = 1
```

**Comment by uknbr** [comment]
Please check the capacity issue part of https://github.com/jpetazzo/ampernetacle#possible-errors-and-how-to-address-them
You need to change default availability domain since there are many people already allocating resources.

**Comment by htschannerl** [comment]
I had the same problem, but the interesting is if I use one account with credits works.
Both accounts are using the same region.

**Comment by marlonklc** [comment]
> amigo, eu tive o mesmo problema, essa mensagem é de que o provedor está sem capacidade, eu reduzi as instâncias para as capacidades mínimas para funcionar, conforme o trecho de código abaixo presente no variables.tf:
> 
> ```
> variable "how_many_nodes" {
>   type    = number
>   default = 1
> }
> 
> variable "availability_domain" {
>   type    = number
>   default = 0
> }
> 
> variable "ocpus_per_node" {
>   type    = number
>   default = 1
> }
> 
> variable "memory_in_gbs_per_node" {
>   type    = number
>   default = 1
> ```

here also the problem happened even if I put the minimum memory .... **Brazil/são paulo** its sucks !

**Comment by jpetazzo** [comment]
I have added this error (and possible workarounds) to the README:

https://github.com/jpetazzo/ampernetacle#capacity-issue

If other folks run into this problem, I'd recommend to just create another account in a different region. For now it seems the easiest solution alas!
