### ISSUE TITLE
Can't make ingress-nginx to work

### ISSUE THREAD

**Issue by rafaelzimmermann** [jpetazzo/ampernetacle#24]
Have anyone managed to configure the ingress-nginx? The ExternalIP is pedding.

looks like it is not able to acquire the external IP

```
EXTERNAL-IP
<pending>
```

I followed this tutorial https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengsettingupingresscontroller.htm

**Comment by fserve** [comment]
Hello, i have made ingress works, i`ve used this project to learn kubernetes, and ingress-nginx was something that i could make work, check here: https://github.com/jpetazzo/ampernetacle/pull/8

**Comment by rafaelzimmermann** [comment]
Thanks!!!! ❤️
