### ISSUE TITLE
Error: 401-NotAuthenticated

### ISSUE THREAD

**Issue by claudiovenancio** [jpetazzo/ampernetacle#27]
Fala mano tudo bem ?

Segui o tutorial, mas estou recebendo esse erro abaixo, Obs: realizei o procedimento de autenticação.

rror: 401-NotAuthenticated 
│ Provider version: 4.62.0, released on 2022-02-03. This provider is 6 Update(s) behind to current. 
│ Service: Identity Compartment 
│ Error Message: The required information to complete authentication was not provided or was incorrect. 
│ OPC request ID: 6896d399fbe98c2a8d4a0000024e3c4e/FF5DB833AF94E0780D65ADD29DC5BB23/FC4D1847A432E5D1A24DE646355D04A2 
│ Suggestion: Please retry or contact support for help with service: Identity Compartment
│ 
│ 
│   with oci_identity_compartment._,
│   on main.tf line 1, in resource "oci_identity_compartment" "_":
│    1: resource "oci_identity_compartment" "_" {

Pode dar uma ajuda por favor ?

Obrigado.

**Comment by BillPelegrini** [comment]
Mesmo problema aqui, estou tentando rodar a partir do proprio cloud Shell do oci:

  with oci_identity_compartment._,
│   on main.tf line 1, in resource "oci_identity_compartment" "_":
│    1: resource "oci_identity_compartment" "_" {

**Comment by jpetazzo** [comment]
Olá! Você pode incluir os comandos que você usou para autenticar? E sua saída? O que será que poderia ter dado errado? Obrigado!

**Comment by jonathanbrito2** [comment]
Boa noite pessoal,

No meu caso o tenancy_id estava errado. Tem que ter bastante atenção com o arquivo de autenticação para não errar nenhum OCID.

**Comment by nerdtux** [comment]
Para resolver execute o seguinte:

`rm ~/.oci/config`
`oci session authenticate`

Vai remover o arquivo de autenticação anterior.
Após você irá logar com o profile padrão.

**Comment by Delfinoln** [comment]
> Para resolver execute o seguinte:
> 
> `rm ~/.oci/config` `oci session authenticate`
> 
> Vai remover o arquivo de autenticação anterior. Após, você irá logar com o profile padrão.

Funcionou perfeitamente! Esse era o problema!
