### ISSUE TITLE
add Kubernetes Cloud Controller Manager oracle cloud 

### ISSUE THREAD

**Issue by ronaldo-barros** [jpetazzo/ampernetacle#3]
hi

https://github.com/oracle/oci-cloud-controller-manager

**Comment by ronaldo-barros** [comment]
ok

**Comment by jpetazzo** [comment]
Hi!

Thanks, I think it would be very interesting to add it, but it seems pretty complicated to automate it 100%.

I'm going to add a note to the README though.

Thanks again!
