### ISSUE TITLE
OCI Authenticate

### ISSUE THREAD

**Issue by alessonviana** [jpetazzo/ampernetacle#30]
Hey @jpetazzo first thank you for this job!
I'm trying to create a CI pipeline on Github Actions using terraform.
The problem is that before applying, we need to configure the credentials in the OCI, but in the manual process, we are directed to the Oracle dashboard to confirm our credentials.
Do you have any idea how I can automate this within a pipeline?

**Comment by docv266** [comment]
Hi

I'm trying also to automate it with Gitlab.
You have to add a provider block with the credentials:

```
provider "oci" {
  tenancy_ocid = var.Tenancy_OCID
  user_ocid = var.User_OCID
  region = "eu-marseille-1"
  private_key = var.PRIVATE_KEY
  fingerprint = var.Fingerprint
}
```

The tenancy and user OCID can be found on the Oracle cloud portal.
You have to generate a public/private key pair along with a fingerprint and provide it too.

**Comment by jpetazzo** [comment]
Thanks for the answer @docv266!

For @alessonviana or anyone else trying to do this, it looks like the following documentation page has details about the procedure:

https://docs.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm#Required_Keys_and_OCIDs
