### ISSUE TITLE
Oracle deleted my account with no explanations and no replies

### ISSUE THREAD

**Issue by lara-marinelli** [jpetazzo/ampernetacle#38]
My instances have been deleted.
If I ask Oracle, the chat is ended immediately after this message:

System terminated your account and unfortunately we can't reactivate or restore the account. Thank you for chatting with us. Have a good day.

**Comment by lara-marinelli** [comment]
For those ones that suffered the same:
https://arminnikdel.medium.com/oracle-cloud-and-loss-of-data-in-kubernetes-cluster-198d88181829

**Comment by jpetazzo** [comment]
I'm going to close this issue because unfortunately this is not something that I can do anything about :( 

But I hope that the problem didn't happen again, or that we at least have explanations.
