### ISSUE TITLE
Failed to connect to : Connection refused

### ISSUE THREAD

**Issue by humbertocrispim** [jpetazzo/ampernetacle#43]
After creating the VMS in the OCI, this loop appears and does not go to the next step

null_resource.wait_for_kube_apiserver (local-exec): curl: (7) Failed to connect to 132.226.252.238 port 6443 after 78 ms: Connection refused

![image](https://user-images.githubusercontent.com/79642492/189545963-9bd028c2-0500-436d-bd09-a268cbf8810b.png)

**Comment by antonsatskyi** [comment]
same here

**Comment by antonsatskyi** [comment]
in fact on Oracle  side
Instance list is  empty

**Comment by RMorgado** [comment]
Same here :(

**Comment by marlonleite** [comment]
same here :(

**Comment by andreixhz** [comment]
same here :(

**Comment by weskhel** [comment]
same here :(

**Comment by JandersonFB** [comment]
same here :'(

**Comment by jpetazzo** [comment]
Hi! Please try again with the latest version (make sure to `git pull`!) as I just pushed a bunch of updates that should improve the process a lot.

Also, now Terraform will show the cloud-init progress; I hope it will give a better idea about what's going on, especially in case of problems!

**Comment by JandersonFB** [comment]
All nodes started:
![image](https://user-images.githubusercontent.com/11274709/209234783-9d28c7f3-207b-4f17-a103-3ce153472385.png)

but, weave nets Crash:
![image](https://user-images.githubusercontent.com/11274709/209234734-9fe19fcd-041d-4d2c-8e2c-4313d0261a92.png)

**Comment by RMorgado** [comment]
I'm using the latest version and I have this error:
![Captura de ecrã 2022-12-23, às 15 44 38](https://user-images.githubusercontent.com/14938665/209362469-e29292ab-076f-444e-91ff-69ba2a933c61.png)

**Comment by jpetazzo** [comment]
@JandersonFB Sorry about that - I got the wrong Weave YAML URL. I was using https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml instead of https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s-1.11.yaml. I've fixed the Terraform configuration and hopefully it should work now. Make sure you have the latest commits and after recreating the VMs it should work!

**Comment by jpetazzo** [comment]
@RMorgado ah that's an interesting error. Do you get the same error for all 4 instances or just the first one? I wonder if that could be a transient error; i.e. if you try again after a while it will work? (Perhaps delete the VM and recreate it with Terraform; or use `terraform taint`? Let me know if you need help for that!)

**Comment by RMorgado** [comment]
Yes @jpetazzo , I have the error in all instances.
I've tested it several times and on different days.
I entered an instance and ran the command "kubectl get nodes " and I got this error:
![error_cloud](https://user-images.githubusercontent.com/14938665/209483840-9c06ba5f-d417-4199-8dba-3f6ec656a95c.png)

I can send more information if you need it.
Thank you for your time and patience

**Comment by hebertviana** [comment]
Hello, first thanks for the work @jpetazzo, I'm having the same problem as @RMorgado.

I'm trying to identify the reason, at night I'll perform new tests if I get a solution I'll update here.

**Comment by hebertviana** [comment]
@jpetazzo and @RMorgado,

To solve the problem, I upgraded the provider version in _provider.tf_ or **oracle/oci** to the latest version "**4.102.0**" (only that didn't work for me, I was in version **0.14.8** of terraform), I did the upgrade from terraform to **v1.3.6** and successfully run terraform.

```sh
Apply complete! Resources: 5 added, 1 changed, 4 destroyed.
```

**Comment by RMorgado** [comment]
Thank you for your help @hebertviana !!!
I made the changes you said and updated terraform to the latest version and it worked!! 

But I still get this error, I'll have to investigate to see if it's firewall issues
![erro_kubectl_get_nodes](https://user-images.githubusercontent.com/14938665/210023705-cda3a5d1-27b8-4e0c-b0c5-d13e4de1e77c.png)

If I enter one of the nodes everything is ok!

**Comment by hebertviana** [comment]
@RMorgado, 

Uhuu, glad it worked.

see if I managed to run this script to release the ports on the firewall, from what I saw here it is in /etc/cloud init/scripts

1-allow-inbound-traffic.sh

**Comment by jpetazzo** [comment]
Hi everyone! It looks like an extra firewalling rule had been added to the Oracle images. I removed that rule (in commit 0a82500) and it looks like it solved it. Let me know if it works for you!

**Comment by alessonviana** [comment]
Hey I updated my fork, and I compared the files, and seems like the same. but I'm still getting the same error 
![image](https://github.com/jpetazzo/ampernetacle/assets/63756788/34012f5a-13f9-4ae0-b32c-cbfe2d822af7)

**Comment by OmarStewey** [comment]
> Hey I updated my fork, and I compared the files, and seems like the same. but I'm still getting the same error ![image](https://private-user-images.githubusercontent.com/63756788/324967649-34012f5a-13f9-4ae0-b32c-cbfe2d822af7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1ODU1NTksIm5iZiI6MTcyNTU4NTI1OSwicGF0aCI6Ii82Mzc1Njc4OC8zMjQ5Njc2NDktMzQwMTJmNWEtMTNmOS00YWUwLWIzMmMtY2JmZTJkODIyYWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAxMTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxZGM0ZDM2NWNkZjM3Mjc3YmExNGNiODNmZmExNjcyYWY0NGZiYjk2NDAyMjdlYzQzMmQzODI1ZjNmODg3MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1gwPIInHez-g7wMnQZtWceU8Tz7XgQoftMhML0JCbWM)

Did you ever find a fix for this? I'm experiencing the same thing.
