### ISSUE TITLE
local-exec provisioner error

### ISSUE THREAD

**Issue by KesleyDavid** [jpetazzo/ampernetacle#5]
Pessoal, quando executo o `terraform apply`, todo processo é inicializado.
Depois de um bom tempo criando os recursos, acontece uma falha.
Ja tentei destruir e criar tudo novamente, mas sempre aparece o mesmo erro.

Alguem sabe como resolver?

Erro:
```
local_file.kubeconfig (local-exec): /bin/sh: 1: kubectl: not found
╷
│ Error: local-exec provisioner error
│ 
│   with local_file.kubeconfig,
│   on kubeconfig.tf line 34, in resource "local_file" "kubeconfig":
│   34:   provisioner "local-exec" {
│ 
│ Error running command 'kubectl --kubeconfig=kubeconfig config set-cluster kubernetes --server=https://IP_IP_IP_IP:6443': exit status 127. Output: /bin/sh: 1: kubectl: not found
│ 
╵
```

Por alguma razão, não é encontrado o kubectl na vm
`/bin/sh: 1: kubectl: not found`

**Comment by KesleyDavid** [comment]
Eu descobri, na realidade, eu preciso ter o k8s instalado na minha maquina local.

Fica a dica para quem encontrar o mesmo erro

**Comment by jpetazzo** [comment]
Muito obrigado! 🙏🏻
