### ISSUE TITLE
Destroy - Delete compartment

### ISSUE THREAD

**Issue by ascosmo** [jpetazzo/ampernetacle#56]
Hello,
I tried destroying and recreating the cluster again, but it doesn't allow me to create the same compartment with the same name kubernetes-on-arm-with-oracle and I can't delete the compartment in OCI.

I tried to recreate it as kubernetes-on-arm-with-oracle-new but there is no resource to create a new compartment.

I have already deleted all the resources from the compartment and it does not finish.

I've done a lot of testing and research, but I haven't been successful.

Could you help with deleting the compartment to recreate the cluster?
Thank you for helping with this repository.

Regards,

**Comment by ascosmo** [comment]
Output.

Error: 409-CompartmentAlreadyExists, A compartment with name 'kubernetes-on-arm-with-oracle' already exists.
│ Suggestion: The resource is in a conflicted state. Please retry again or contact support for help with service: Identity Compartment
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/identity_compartment
│ API Reference: https://docs.oracle.com/iaas/api/#/en/identity/20160918/Compartment/UpdateCompartment

**Comment by jpetazzo** [comment]
Hi!

Sometimes it takes a while do delete the compartment - I don't know why.

The easiest option would be to create a new compartment with a different name... What's the error that you got when you tried that?

**Comment by ascosmo** [comment]
Thank you for the informations.

I looked for several ways to delete the compartments, but I couldn't find them.
I didn't find a solution to delete the compartments, no resources linked to the compartment were found and it still couldn't be deleted.

Thanks.

**Comment by ascosmo** [comment]
Thanks.
