### ISSUE TITLE
Error on apply

### ISSUE THREAD

**Issue by ralphtacconi** [jpetazzo/ampernetacle#9]
Estou tomando esse erro:
 Error: 401-NotAuthenticated
│ Provider version: 4.57.0, released on 2021-12-15. This provider is 7 version(s) old.
│ Service: Identity Compartment
│ Error Message: The required information to complete authentication was not provided or was incorrect.
│ OPC request ID: 9fda6778a33ef339ee589cdb35a0a10a/A7AB78B271531D65FC2D3174CE369407/45C30A48916D485C5628D83D0FB8987F
│ Suggestion: Please retry or contact support for help with service: Identity Compartment

Fiz a autenticação certo.,...

Podem me ajudar?

**Comment by fserve** [comment]
Ralph, i got the same problem, when using oci sessino authenticate, it will ask to create an profile, i just wrote DEFAULT and it worked. Check your file ~/.oci/config

Ralph, tive esse problema e quando uso o oci session authenticate, vai ter uma hora que ele vai perguntar qual perfil criar, aí eu respondo DEFAULT e costuma funcionar. Verique o arquivo ~/.oci/config

**Comment by ralphtacconi** [comment]
> Ralph, eu tenho o mesmo problema, ao usar o oci sessino authenticate, ele pedirá para criar um perfil, acabei de escrever DEFAULT e funcionou. Verifique seu arquivo ~/.oci/config
> 
> Ralph, tem esse problema e quando usar o oci session autenticar, vai ter uma hora que ele vai perguntar qual perfil criar, aí eu respondo DEFAULT e costuma funcionar. Verifique o arquivo ~/.oci/config

Obrigado amigo. Vou tentar aqui.

**Comment by manoelcamillo** [comment]
@ralphtacconi in my case what happened was that I authenticated with an account with limited access to OCI. What I did to solve the problema was to remove the `~/.oci/config` file, logged out of the limited account in my default browser, ran `oci session authenticate` again and this time I logged in with the user who owned the tenancy.

@ralphtacconi no meu caso o que aconteceu era que eu autentiquei com uma conta com acesso limitado ao OCI. O que eu fiz para resolver foi remover o arquivo `~/.oci/config` desloguei da conta limitada no meu browser default, rodei novamente o `oci session authenticate` e dessa vez fiz o login com o usuário dono da conta

**Comment by amaraldavi1** [comment]
When you guys get this error, make sure to have a valid session. To check if the current session is valid, run:
`oci session validate` 
***
Quando vcs observarem esse erro, verifiquem se a sessão do OCI cli está válida. Para checar isso, basta executar:
`oci session validate`

**Comment by fuentesbr** [comment]
Olá,

estou recebendo esse erro para cada uma das 4 instâncias:

Error: 500-InternalError
│ Provider version: 4.62.0, released on 2022-02-03. This provider is 1 Update(s) behind to current.
│ Service: Core Instance
│ Error Message: Out of host capacity.
│ OPC request ID: d820cdc87981d090289245ae2ca615aa/AAC3BD1E320C0D2CC2DE1953D69687AA/E736F8D74BAC8601946FA41BB8A02C92
│ Suggestion: The service for this resource encountered an error. Please contact support for help with service: Core Instance
│
│
│   with oci_core_instance._["3"],
│   on main.tf line 24, in resource "oci_core_instance" "_":
│   24: resource "oci_core_instance" "_" {

Já refiz o login, pois a minha conta é nova e demorou um tempo até receber o e-mail de Fully Provisioned. Pela mensagem de erro para que não tenho esse serviço, ou estou enganado?

Obrigado.

**Comment by jpetazzo** [comment]
Olá @fuentesbr,

Eu acho que "Out of host capacity" é um problema diferente; significa que não há capacidade suficiente disponível no momento. Você poderia tentar mudar para um "Availability Domain" diferente ou tentar novamente mais tarde.
